[unstable]
build-std = ['std', 'panic_abort']

[build]
target = "wasm32-unknown-unknown"
# rustflags = '-Ctarget-feature=+bulk-memory,+mutable-globals'
rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'
